version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PW}
      POSTGRES_DB: ${DB_NAME}
    restart: always
    ports:
      - '${DB_PORT}:${DB_PORT}'
